# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemesSiteBuilder for more information

name = "Mori"
license = "MIT"
licenselink = "https://github.com/g-mero/hugo-theme-mori/blob/main/LICENSE"
description = "A clean and elegant Hugo theme"
homepage = "https://github.com/g-mero/hugo-theme-mori"
demosite = "https://github.com/g-mero/hugo-theme-mori"
tags = ["blog", "clean", "minimal", "responsive"]
features = ["responsive", "syntax-highlighting"]

[author]
name = "g-mero"
homepage = "https://github.com/g-mero"
