baseURL = 'https://example.org/'
defaultContentLanguage = 'en'
theme = 'hugo-theme-mori'

[pagination]
pagerSize = 5

# Language configuration
[languages]
[languages.en]
languageCode = 'en-US'
languageName = 'English'
title = 'Mori'
weight = 1

[languages.zh-cn]
languageCode = 'zh-CN'
languageName = '简体中文'
title = 'Mori'
weight = 2
